// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEyZK5w7HDCBUf9JpuGHAv06xbCFP6Xoo',
    appId: '1:220785515283:web:2927f79548666499de18e6',
    messagingSenderId: '220785515283',
    projectId: 'flutterapplication1-9d0ef',
    authDomain: 'flutterapplication1-9d0ef.firebaseapp.com',
    storageBucket: 'flutterapplication1-9d0ef.firebasestorage.app',
    measurementId: 'G-MWCL1RB4Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpVTxQjNDn9RTbofstUHqvrb3_JRZsFA',
    appId: '1:220785515283:android:f2c882e0f780e419de18e6',
    messagingSenderId: '220785515283',
    projectId: 'flutterapplication1-9d0ef',
    storageBucket: 'flutterapplication1-9d0ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0N4wNk3fwoUeYuC8QSqMl9yjDK0shVE',
    appId: '1:220785515283:ios:802f9c803e08dc87de18e6',
    messagingSenderId: '220785515283',
    projectId: 'flutterapplication1-9d0ef',
    storageBucket: 'flutterapplication1-9d0ef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0N4wNk3fwoUeYuC8QSqMl9yjDK0shVE',
    appId: '1:220785515283:ios:802f9c803e08dc87de18e6',
    messagingSenderId: '220785515283',
    projectId: 'flutterapplication1-9d0ef',
    storageBucket: 'flutterapplication1-9d0ef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEyZK5w7HDCBUf9JpuGHAv06xbCFP6Xoo',
    appId: '1:220785515283:web:9ced3eb78930c03cde18e6',
    messagingSenderId: '220785515283',
    projectId: 'flutterapplication1-9d0ef',
    authDomain: 'flutterapplication1-9d0ef.firebaseapp.com',
    storageBucket: 'flutterapplication1-9d0ef.firebasestorage.app',
    measurementId: 'G-MM2WPKD22X',
  );

}